p8105\_hw3\_jt3098
================
Jieqi Tu (jt3098)
10/5/2018

Problem 1
---------

``` r
# Importing data from guthub website
devtools::install_github("p8105/p8105.datasets")
```

    ## Skipping install of 'p8105.datasets' from a github remote, the SHA1 (21f5ad1c) has not changed since last install.
    ##   Use `force = TRUE` to force installation

``` r
library(p8105.datasets)
data(brfss_smart2010, package = "p8105.datasets")
```

``` r
brfss_smart2010 = 
  brfss_smart2010 %>%
  janitor::clean_names() %>% # Change upper-case letter to lower-case letter
  filter(topic == "Overall Health") %>% # Focus on the topic of Overall Health
  filter(response %in% c("Excellent", "Very good", "Good", "Fair", "Poor"))
```

``` r
brfss_smart2010$response = factor(brfss_smart2010$response, 
                                  levels = c("Excellent", "Very good", "Good", "Fair", "Poor"))
```

``` r
brfss_smart2002 = 
  brfss_smart2010 %>%
  filter(year == "2002") %>%
  group_by(locationabbr) %>%
  summarise(n_observed_location = n_distinct(geo_location)) %>%
  filter(n_observed_location == 7)
```

In 2002, there 3 states observed in 7 locations. They are Connecticut (CT), Florida (FL), and North Carolina (NC).

``` r
brfss_smart2010 %>%
  group_by(locationabbr, year) %>%
  summarise(n_observation = sum(sample_size)) %>%
  ggplot(aes(x = year, y = n_observation, color = locationabbr)) +
  geom_line(alpha = 0.5) +
  labs(
    title = "Observation Times of Each States from 2002 to 2010",
    y = "Observation Times",
    x = "Year"
  ) + 
  theme_bw()
```

<img src="p8105_hw3_jt3098_files/figure-markdown_github/Spaghetti plot-1.png" width="100%" />

``` r
brfss_prop_020610 = 
  brfss_smart2010 %>%
  filter(year %in% c("2002", "2006", "2010"), response == "Excellent", locationabbr == "NY") %>%
  group_by(year) %>%
  summarise(mean = mean(data_value), standard_deviation = sd(data_value))
```

``` r
brfss_prop_each = 
  brfss_smart2010 %>%
  group_by(year, locationabbr, response) %>%
  summarise(average_proportion = mean(data_value, rm.na = TRUE))

ggplot(brfss_prop_each, aes(x = year, y = average_proportion, color = locationabbr)) +
  geom_line(alpha = 0.5) +
  facet_grid( ~response) +
  labs(
    title = "Average Proportion for Each Response in Every States and Location from 2002 to 2010",
    x = "Year",
    y = "Average Proportion"
  ) +
  scale_x_continuous(
    breaks = c(2004, 2008),
    labels = c("2004", "2008")) +
  theme_bw()
```

    ## Warning: Removed 1 rows containing missing values (geom_path).

<img src="p8105_hw3_jt3098_files/figure-markdown_github/Five-panel Plot-1.png" width="100%" />

Problem 2
---------

``` r
data("instacart", package = "p8105.datasets")
```

``` r
# Calculate the number of aisles
n_aisle = 
  instacart %>%
  distinct(aisle) %>%
  nrow()

# Count the most ordered aisle
count_(instacart, 'aisle', sort = TRUE)
```

    ## # A tibble: 134 x 2
    ##    aisle                              n
    ##    <chr>                          <int>
    ##  1 fresh vegetables              150609
    ##  2 fresh fruits                  150473
    ##  3 packaged vegetables fruits     78493
    ##  4 yogurt                         55240
    ##  5 packaged cheese                41699
    ##  6 water seltzer sparkling water  36617
    ##  7 milk                           32644
    ##  8 chips pretzels                 31269
    ##  9 soy lactosefree                26240
    ## 10 bread                          23635
    ## # ... with 124 more rows

About this dataset:

-   This instacart dataset has 15 variables in total. It includes user ID, product ID, order number, order hour of day, days since prior order, etc.
-   The mean of order hour of day is 13.5775922, and the standard deviation of order hour of day is 4.238458.
-   The mean of days since prior order is 17.0661259, and the standard deviation of days since prior order is 10.4264178.
-   The number of aisle is 134, and the aisle that most items ordered from is fresh vegetables with 150609 orders.

``` r
instacart %>%
  group_by(aisle_id) %>%
  summarise(total_aisle = n()) %>%
  ggplot(aes(x = aisle_id, y = total_aisle)) +
  geom_point(alpha = 0.5) +
  labs(
    x = "Aisle ID",
    y = "Number of Items Ordered",
    title = "Number of Items Ordered in Each Aisle"
  ) +
  scale_x_continuous(
    breaks = c(0, 25, 50, 75, 100, 125, 150),
    labels = c("0", "25", "50", "75", "100", "125", "150")
  ) +
  theme_bw()
```

<img src="p8105_hw3_jt3098_files/figure-markdown_github/plots of number of items ordered in each aisle-1.png" width="100%" />
